#!/usr/bin/env php
<?php

$opts = getopt("b");

$birthDate =$opts["b"] ?? "1977-08-10";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtoTime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 /24);

echo "$birthDate : $totalDays" . PHP_EOL;
