#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

$opts = getopt("b");

$birthDate =$opts["b"] ?? "1977-08-10";
$days = new Splx\Dates\BirthDays($birthDate);

$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays" . PHP_EOL;
